"""ORM models for the English exam bot.

Schema overview
---------------
users              telegram users
passages           reading passages / cloze texts (shared by many questions)
questions          single 4-option question, optionally tied to a passage
exam_sessions      one attempt by one user (timer, score, status)
session_questions  ordered snapshot of the questions in a session + answers
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


# --- enumerated string values (kept as plain strings for migration simplicity) ---
class Origin:
    BANK = "bank"   # extracted from a real past konkoor exam
    AI = "ai"       # freshly generated by OpenAI


class SkillType:
    GRAMMAR = "grammar"
    VOCABULARY = "vocabulary"
    CLOZE = "cloze"
    READING = "reading"
    ALL = (GRAMMAR, VOCABULARY, CLOZE, READING)


class SourceKind:
    BANK = "bank"
    AI = "ai"


class SessionStatus:
    IN_PROGRESS = "in_progress"
    FINISHED = "finished"
    EXPIRED = "expired"


class User(Base):
    __tablename__ = "users"

    telegram_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    username: Mapped[str | None] = mapped_column(String(64))
    first_name: Mapped[str | None] = mapped_column(String(128))
    language_code: Mapped[str | None] = mapped_column(String(8))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    last_active_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    sessions: Mapped[list["ExamSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Passage(Base):
    __tablename__ = "passages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    source: Mapped[str] = mapped_column(String(64), index=True)  # e.g. konkoor-1402
    year: Mapped[int | None] = mapped_column(Integer, index=True)
    title: Mapped[str | None] = mapped_column(String(255))
    body: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    questions: Mapped[list["Question"]] = relationship(back_populates="passage")


class Question(Base):
    __tablename__ = "questions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    passage_id: Mapped[int | None] = mapped_column(
        ForeignKey("passages.id", ondelete="SET NULL"), index=True
    )
    origin: Mapped[str] = mapped_column(String(16), index=True, default=Origin.BANK)
    source: Mapped[str | None] = mapped_column(String(64), index=True)
    year: Mapped[int | None] = mapped_column(Integer, index=True)
    number: Mapped[int | None] = mapped_column(Integer)  # 1..30 in original booklet
    skill_type: Mapped[str] = mapped_column(String(16), default=SkillType.GRAMMAR)
    stem: Mapped[str] = mapped_column(Text)
    options: Mapped[list[str]] = mapped_column(JSONB)  # exactly 4 strings
    correct_index: Mapped[int] = mapped_column(Integer)  # 0..3
    explanation: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    passage: Mapped["Passage | None"] = relationship(back_populates="questions")


class ExamSession(Base):
    __tablename__ = "exam_sessions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.telegram_id", ondelete="CASCADE"), index=True
    )
    source_kind: Mapped[str] = mapped_column(String(16), default=SourceKind.BANK)
    source_label: Mapped[str | None] = mapped_column(String(64))

    num_questions: Mapped[int] = mapped_column(Integer)
    duration_seconds: Mapped[int] = mapped_column(Integer)

    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    deadline_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    status: Mapped[str] = mapped_column(
        String(16), default=SessionStatus.IN_PROGRESS, index=True
    )
    current_position: Mapped[int] = mapped_column(Integer, default=0)
    correct_count: Mapped[int] = mapped_column(Integer, default=0)
    score: Mapped[float | None] = mapped_column(Float)  # percentage 0..100

    # Telegram coordinates of the single in-place exam message (for timer /
    # restart recovery — lets the bot re-find and edit the live exam message).
    tg_chat_id: Mapped[int | None] = mapped_column(BigInteger)
    tg_message_id: Mapped[int | None] = mapped_column(BigInteger)

    user: Mapped["User"] = relationship(back_populates="sessions")
    items: Mapped[list["SessionQuestion"]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="SessionQuestion.position",
    )


class SessionQuestion(Base):
    __tablename__ = "session_questions"
    __table_args__ = (
        UniqueConstraint("session_id", "position", name="uq_session_position"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    session_id: Mapped[int] = mapped_column(
        ForeignKey("exam_sessions.id", ondelete="CASCADE"), index=True
    )
    question_id: Mapped[int] = mapped_column(
        ForeignKey("questions.id", ondelete="CASCADE")
    )
    position: Mapped[int] = mapped_column(Integer)  # 0-based order within the exam
    selected_index: Mapped[int | None] = mapped_column(Integer)  # 0..3
    is_correct: Mapped[bool | None] = mapped_column(Boolean)
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    session: Mapped["ExamSession"] = relationship(back_populates="items")
    question: Mapped["Question"] = relationship()
