.DEFAULT_GOAL := help
COMPOSE := docker compose

.PHONY: help up down logs ps build restart migrate revision ingest ingest-docker \
        install run-local answer-keys fmt

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

up: ## Build + start everything (db, migrations, bot). The only command you need.
	$(COMPOSE) up -d --build

down: ## Stop and remove containers (keeps the database volume)
	$(COMPOSE) down

logs: ## Tail the bot logs
	$(COMPOSE) logs -f bot

ps: ## Show running services
	$(COMPOSE) ps

build: ## Rebuild images
	$(COMPOSE) build

restart: ## Restart the bot service
	$(COMPOSE) restart bot

migrate: ## Run DB migrations (schema + seed) inside the bot image
	$(COMPOSE) run --rm bot migrate

revision: ## Create a new autogenerated migration: make revision m="message"
	$(COMPOSE) run --rm bot alembic revision --autogenerate -m "$(m)"

ingest: ## Run OCR ingestion locally (needs local Python env + exams/ + OPENAI key)
	python -m app.ingestion.ingest $(ARGS)

ingest-docker: ## Run ingestion in Docker, mounting the local exams/ folder
	$(COMPOSE) run --rm -v $(PWD)/exams:/app/exams -v $(PWD)/app/data:/app/app/data bot ingest $(ARGS)

answer-keys: ## Regenerate app/data/answer_keys.json from the answer-key PDFs (no API)
	python -m app.ingestion.ingest --dry-run

install: ## Create a local virtualenv and install deps
	python3 -m venv .venv && . .venv/bin/activate && pip install -U pip && pip install -r requirements.txt

run-local: ## Run the bot from the local env (expects a reachable Postgres)
	python -m app.bot.main

fmt: ## Quick syntax check of all modules
	python -m compileall -q app alembic
